name: Sample worlflow build

on:
  push:
    branches:
      - main

jobs:
  Javabuildjob:
    runs-on: ubuntu-latest
    steps:
    - name: javabuildsetup
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - run: java HelloWorldApp.java
