name: Sample worlflow build

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  

jobs:
  sampleworkflowbuildjob:
    runs-on: ubuntu-latest
    steps: 
    - name: TestJobBuild
      uses: actions/checkout@v4
  sampleworkflowbuildjob2:
    runs-on: macos-latest
    steps:
    - name: TestJobBuildMacOs
      uses: actions/checkout@v4
  sampleworkflowbuildjob2:
    runs-on: windows-latest
    steps:
    - name: TestJobBuildwindows
      run: echo Hello


